version: '3'
services:
    web:
        image: node:11-alpine
        working_dir: /app
        volumes:
            - .:/app
        command: ash -c 'yarn && yarn run dev'
        ports:
            - 3000:3000
